name: Deploy

on:
  push:
    branches:
      - api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spam-ham-api"
          heroku_email: "aymaneboumaaza@gmail.com"
